department-of-veterans-affairs/health-apis-data-query

README.md
mr-anderson/README.md
mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/Query.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/ResourceRepository.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/Resources.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/impl/IdentityParameterReplacer.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/impl/InPlaceReferenceReplacer.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/impl/ResourceIdentities.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/impl/ResourceNameTranslation.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/impl/SqlResourceRepository.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/impl/WitnessProtectionResources.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/impl/XmlResponseValidator.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/ids/client/RestIdentityServiceClient.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/util/Checks.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/util/Parameters.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/util/XmlDocuments.java
sentinel/README.md

No real code changes, just documentation and a little formatting.

Task/api 117 Mr. Anderson docs

---

argonaut-api/src/main/java/gov/va/api/health/argonaut/api/Patient.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/validation/ArgoRaceExtensionValidationTest.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/validation/SampleExtensions.java

https://vasdvp.atlassian.net/browse/API-133
- Added validation for patients with an argo-race extension
- Created tests and sample data to ensure validation works

added validation for race extensions and tests with sample data

---

argonaut-api/pom.xml
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/ConfigurableBaseUrlPageLinks.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/PageLinks.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/Parameters.java
argonaut/src/main/resources/application.properties
argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/ConfigurableBaseUrlPageLinksTest.java
argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/ParametersTest.java
src/scripts/make-configs.sh

- part of the patient bundler stuff, this adds a link creator for use with bundles
- Adds new configurable: `argonaut.url`
- the `make-configs` script will default this to localhost

Argonaut - Added bundle link maker

---

argonaut-api/src/main/java/gov/va/api/health/argonaut/api/Medication.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/MedicationBundleTest.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/PatientBundleTest.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/SampleDataTypes.java

Medication.Bundle support in Argonaut-API

Medication bundle and tests, and refactored patient bundle test

---

argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/EnumSearcher.java
argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/EnumSearcherTest.java

Generic Enum searcher to support @JsonProperty as well as @name values.

Enum searcher

---

argonaut-api/src/main/java/gov/va/api/health/argonaut/api/datatypes/Age.java
argonaut-api/src/main/java/gov/va/api/health/argonaut/api/datatypes/Duration.java
argonaut-api/src/main/java/gov/va/api/health/argonaut/api/datatypes/Timing.java
argonaut-api/src/main/java/gov/va/api/health/argonaut/api/resources/MedicationOrder.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/resources/MedicationOrderTest.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/samples/SampleDataTypes.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/samples/SampleMedicationOrders.java

API model for Medication Order resource has been added to argonaut-api project.
Related story:
https://vasdvp.atlassian.net/browse/API-383

Task/API 383 Add Medication Order API Model

---

argonaut-api/src/main/java/gov/va/api/health/argonaut/api/resources/Organization.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/resources/OrganizationTest.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/samples/SampleOrganizations.java

Organization model has been added to argonaut-api project. Includes Organization class, sample data, and test. 
Related story: https://vasdvp.atlassian.net/browse/API-427

Task/API 427 Create Organization Model

---

argonaut-api/src/main/java/gov/va/api/health/argonaut/api/resources/Appointment.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/resources/AppointmentTest.java
argonaut-api/src/test/java/gov/va/api/health/argonaut/api/samples/SampleAppointments.java

Appointment Model

---

mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/impl/SqlResourceRepository.java
mr-anderson/src/main/resources/application.properties
mr-anderson/src/test/java/gov/va/api/health/mranderson/cdw/impl/SqlResourceRepositoryTest.java

By default the following is assumed
```
cdw.stored-procedure=prc_Entity_Return
```
A request has been made to update Mr. Anderson configuration in Staging to use `prc_resource_return` in  the Mitre DB

Adds configurable property to Mr. Anderson to change the stored procedure

---

argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/medicationstatement/MedicationStatementControllerTest.java

changed 
getClass().getResourceAsStream("/cdw/old-medicationStatement-1.02.json")
to be
getClass().getResourceAsStream("/cdw/old-medicationstatement-1.02.json")

change file name to match file

---

argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/allergyintolerance/AllergyIntoleranceController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/appointment/AppointmentController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/condition/ConditionController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/diagnosticreport/DiagnosticReportController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/encounter/EncounterController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/immunization/ImmunizationController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/location/LocationController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medication/MedicationController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medicationorder/MedicationOrderController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medicationstatement/MedicationStatementController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/observation/ObservationController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/organization/OrganizationController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/patient/PatientController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/practitioner/PractitionerController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/procedure/ProcedureController.java
sentinel/src/main/java/gov/va/health/api/sentinel/ExpectedResponse.java
sentinel/src/main/java/gov/va/health/api/sentinel/FhirTestClient.java
sentinel/src/test/java/gov/va/health/api/sentinel/ArgonautReadAndSearchIT.java

Fixes page and _count values that are out of bounds...
1 < page <= inf
1 <= _count <= 20

Added page and _count bounds enforcement on all controllers

---

argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/allergyintolerance/AllergyIntoleranceController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/appointment/AppointmentController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/condition/ConditionController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/diagnosticreport/DiagnosticReportController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/encounter/EncounterController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/immunization/ImmunizationController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/location/LocationController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medication/MedicationController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medicationorder/MedicationOrderController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medicationstatement/MedicationStatementController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/observation/ObservationController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/organization/OrganizationController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/patient/PatientController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/practitioner/PractitionerController.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/procedure/ProcedureController.java
sentinel/src/main/java/gov/va/health/api/sentinel/FhirTestClient.java
sentinel/src/main/java/gov/va/health/api/sentinel/mockcdw/MockCall.java
sentinel/src/main/java/gov/va/health/api/sentinel/mockcdw/MockResponseSource.java
sentinel/src/test/java/gov/va/health/api/sentinel/ArgonautReadAndSearchIT.java
sentinel/src/test/resources/cdw/index.yaml

Mock CDW driver will now loosely match queries when count == 0 or greater than 20 when patient or identifier values match.

Argonaut now allows `0 <= _count <= 20` for all resources

---

argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/encounter/EncounterController.java

Related story: https://vasdvp.atlassian.net/browse/API-491

Switch to ARGONAUT to DSTU2

---

argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/allergyintolerance/AllergyIntoleranceTransformer.java
argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/allergyintolerance/AllergyIntoleranceTransformerTest.java

fix substance coding null pointer.
related story: https://vasdvp.atlassian.net/browse/API-508

task/API-508 Fix Allergy Intolerance Transformer Null Pointer

---

sentinel/pom.xml
sentinel/src/main/docker/Dockerfile
sentinel/src/main/docker/assembly.xml
sentinel/src/main/docker/entrypoint.sh
sentinel/src/main/java/gov/va/health/api/sentinel/IdMeOauthRobot.java
sentinel/src/main/java/gov/va/health/api/sentinel/crawler/FileResultsCollector.java
sentinel/src/main/java/gov/va/health/api/sentinel/crawler/Result.java
sentinel/src/main/java/gov/va/health/api/sentinel/crawler/ResultCollector.java
sentinel/src/main/java/gov/va/health/api/sentinel/crawler/SummarizingResultCollector.java
sentinel/src/test/java/gov/va/health/api/sentinel/LabTest.java
sentinel/src/test/resources/logback-test.xml

- Adds verifications to lab crawler tests
- Adds summary logging to lab crawler tests
- Adds docker packaging and utilities to execute tests
- New jar shader produces a _fat_ jar that includes all the dependencies. Some `test` scope dependencies were upgraded to `compile` to be included in the shaded jar
- New test jar which include test classes

Sentinel docker support

---

argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/conformance/MetadataController.java
argonaut/src/test/resources/old-conformance.json

Reverts department-of-veterans-affairs/health-apis#118

Revert "task/API-604 Update the Jargonaut Smart-On-Fhir documentation link in conformance"

---

sentinel/pom.xml

This will stop docker image build in local environments, Jenkins automatically applies the `release` profile.

Sentinel now builds th docker container only in release profile

---

sentinel/src/main/java/gov/va/health/api/sentinel/Sentinel.java
sentinel/src/main/java/gov/va/health/api/sentinel/SystemDefinitions.java
sentinel/src/main/java/gov/va/health/api/sentinel/TestIds.java

In preparation of allowing sentinel to run in the PROD and QA environments, SystemDefinitions are added for each. Related Story: https://vasdvp.atlassian.net/browse/API-668

Task/API 668 Singular Specific Test Data to Set

---

sentinel/src/test/java/gov/va/health/api/sentinel/AllergyIntoleranceIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/AppointmentIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/ConditionIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/DiagnosticReportIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/EncounterIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/ImmunizationIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/LocationIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/MedicationIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/MedicationOrderIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/MedicationStatementIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/ObservationIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/OrganizationIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/PractitionerIT.java
sentinel/src/test/java/gov/va/health/api/sentinel/ProcedureIT.java

Moved _id and identifier tests out of the PROD category.

refatored test categories

---

sentinel/src/test/java/gov/va/health/api/sentinel/PatientIT.java

Added missing Category(Prod.class)
Refactored _id='unknown' test to handle both QA/PROD (403) and LOCAL (404)

missing category tag, and refactored patient test

---

argonaut-api/src/main/java/gov/va/api/health/argonaut/api/datatypes/Coding.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/Transformers.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/allergyintolerance/AllergyIntoleranceTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/appointment/AppointmentTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/condition/ConditionTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/diagnosticreport/DiagnosticReportTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/encounter/EncounterTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/immunization/ImmunizationTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/location/LocationTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medication/MedicationTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medicationdispense/MedicationDispenseTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medicationorder/MedicationOrderTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medicationstatement/MedicationStatementTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/observation/ObservationTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/organization/OrganizationTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/patient/PatientTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/practitioner/PractitionerTransformer.java
argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/procedure/ProcedureTransformer.java
argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/TransformersTest.java
argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/medication/MedicationTransformerTest.java

Replace `Transformers.allNull()` with `allBlank()`.
Update builder constructor for `Coding` to replace blank strings with nulls.

API-714 Handle medication code empty string.

---

src/scripts/dev-app.sh

Related Story : https://vasdvp.atlassian.net/browse/API-792

fix dev script for Windows

---

sentinel/src/main/java/gov/va/health/api/sentinel/IdMeOauthRobot.java
sentinel/src/main/java/gov/va/health/api/sentinel/LabRobots.java
sentinel/src/test/java/gov/va/health/api/sentinel/CdwCrawlerTest.java
sentinel/src/test/java/gov/va/health/api/sentinel/LabCrawlerTest.java

Allow for patients to be specified as a command line argument. 
Related story: https://vasdvp.atlassian.net/browse/API-743

Task/API-743 99 Red Patients

---

argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/procedure/ProcedureController.java
argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/procedure/ProcedureControllerTest.java

https://vasdvp.atlassian.net/browse/API-814

API-814 procedure hack jargonaut

---

argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/procedure/ProcedureController.java
argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/procedure/ProcedureControllerTest.java

https://vasdvp.atlassian.net/browse/API-814

API-814 Follow-up: support replacement of patient display in procedure hack

---

sentinel/src/main/java/gov/va/health/api/sentinel/IdMeOauthRobot.java

Related Story: https://vasdvp.atlassian.net/browse/API-876

remove in method declarations

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/AppointmentTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/ConditionTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/LocationTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationorder/MedicationOrderTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationstatement/MedicationStatementTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/ObservationTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureTransformer.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/util/XmlDocuments.java

https://vasdvp.atlassian.net/browse/API-993
Address Fortify findings. Remove unnecessary `null` checks and disable XML external entity injection.

API-993 Fortify findings

---

data-query-api/src/main/java/gov/va/api/health/dataquery/api/validation/ExactlyOneOf.java
data-query-api/src/main/java/gov/va/api/health/dataquery/api/validation/ZeroOrOneOf.java

Edit checkstyle warnings for a stable build.
Related story: https://vasdvp.atlassian.net/browse/API-1163

Task/API-1163 Edit checkstyle warnings

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/MrAndersonIT.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/AppointmentController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/ConditionController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/conformance/MetadataController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/EncounterController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/LocationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medication/MedicationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationdispense/MedicationDispenseController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationorder/MedicationOrderController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationstatement/MedicationStatementController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/ObservationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/OrganizationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/wellknown/WellKnownController.java
mr-anderson/src/main/java/gov/va/api/health/mranderson/controller/MrAndersonV1ApiController.java

Related Story : https://vasdvp.atlassian.net/browse/ADQ-44
- Added the new / path alongside the deprecated /api path until we are sure it is no longer needed.

added a / path along side of the /api path

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java
data-query/src/main/java/gov/va/api/health/dataquery/service/api/DataQueryService.java

https://vasdvp.atlassian.net/browse/ADQ-43
Updating our Swagger to the new hotness

Update Swagger Server

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/ObservationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureControllerTest.java

- Fixed Observation Category Search
- Standardized optional parameters across controllers 
- Improved unit tests

Fixed Observation Category Search. 

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureControllerTest.java

Related Story: https://vasdvp.atlassian.net/browse/ADQ-66

use icn header to do patient reference substitution on procedure reads

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/WellKnownIT.java

Related Story: [https://vasdvp.atlassian.net/browse/ADQ-35](url)

add lab patient annotation back to wellKnownIT

---

mr-anderson/src/main/java/gov/va/api/health/mranderson/controller/ErrorResponse.java

system.time is now java.time.clock

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/DatamartPatient.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/DatamartPatientTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/DatamartPatientTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/PatientControllerTest.java

https://vasdvp.atlassian.net/browse/ADQ-95
Refinements to Patient datamart transformation logic based on differences observed in QA environment for `1011537977V693883` test patient.

ADQ-95 Patient datamart refinements

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/PatientIT.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/WebExceptionHandler.java

Related story: https://vasdvp.atlassian.net/browse/ADQ-110

map unsatisfiedservletrequestparameterexception to bad request

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/datamart/DatamartReference.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationstatement/DatamartMedicationStatement.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationstatement/DatamartMedicationStatementTest.java
data-query/src/test/resources/gov/va/api/health/dataquery/service/controller/medicationstatement/datamart-medication-statement.json

Java to match https://github.freedomstream.io/mulesoft/cdw-schemas/blob/develop/datamart/medicationStatement-json-example.json
See also https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/232

Datamart Medication Statement model

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/DatamartCondition.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/datamart/DatamartReference.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/condition/DatamartConditionTest.java
data-query/src/test/resources/gov/va/api/health/dataquery/service/controller/condition/datamart-condition.json

Model for https://github.freedomstream.io/mulesoft/cdw-schemas/blob/develop/datamart/condition_json_sample.json

Datamart: Condition model

---

data-query-tests/.gitignore
data-query-tests/pom.xml
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/DataQueryScopes.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/OauthLoginTest.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/crawler/UsingOAuthCrawlerTest.java
data-query/pom.xml
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/immunization/DatamartImmunizationTest.java
mr-anderson/pom.xml
pom.xml

- The lab crawler is now working with latest SNAPSHOT parent
- Login test is now detecting errors
This work is not done. The docker test image needs to be updated to support the new login properties and correct function.

Update lab bots to latest available parent

---

data-query/src/test/java/gov/va/api/health/dataquery/service/controller/immunization/DatamartImmunizationSamples.java

everybody do your share
https://vasdvp.atlassian.net/browse/API-1439

clean up clean up

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/Transformers.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/DatamartAllergyIntolerance.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/DatamartAllergyIntoleranceTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/datamart/DatamartCoding.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/TransformersTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/DatamartAllergyIntoleranceSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/DatamartAllergyIntoleranceTest.java

to prevent cascading deployments from interfering with lab upgrades

Extracts codiing from DatamartAllergyIntolerance to be usable in other models

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/ConditionController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationstatement/MedicationStatementController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureController.java

This PR addresses (at least some) of the QA integration test failures

Support for _count=0 for Datamart resources

---

data-query-tests/pom.xml
data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/WitnessProtection.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/ConditionRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medication/MedicationRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationorder/MedicationOrderRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationstatement/MedicationStatementRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/ObservationRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/healthcheck/SteelThreadSystemCheck.java
mr-anderson/pom.xml
mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/ResourceRepository.java
pom.xml
src/scripts/trust-dev-certs.sh

Do not merge until parent pom versions have been updated.
See https://github.com/department-of-veterans-affairs/health-apis-parent/pull/28

Datamart components now have better logging (using @Loggable)

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/Crawler.java
data-query-tests/src/test/resources/logback-test.xml

which will add the -HDatamart:<value> header if specified to all requests.

Added -Ddatamart=true support to the crawler 

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/Crawler.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/FileResultsCollector.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/Result.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/SummarizingResultCollector.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/crawler/IgnoreFilterResultCollectorTest.java
data-query/src/test/java/gov/va/api/health/dataquery/tools/SqlExecutor.java

Simple command line utility for executing queries

Crawler now prints timing information. 

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/DatamartPatient.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/DatamartPatientTest.java

https://vasdvp.atlassian.net/browse/ADQ-222

optional patient fields

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceTransformerTest.java

Resume mapping recordedDate in allergy intolerance.
Do this: https://vasdvp.atlassian.net/browse/API-1465
Undo this: https://vasdvp.atlassian.net/browse/API-1411

resume mapping recorded date

---

data-query-tests/lab-login
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/OauthLoginTest.java

Tokens are now clearly printed
New utility script to execute login to easily get token for manual testing

Adds ability for OauthLoginTest to process a specific user.

---

data-query/src/test/java/gov/va/api/health/dataquery/service/config/DataQueryJacksonMapperTest.java

- Improved unit test coverage
- Formatting

Improve unit test coverage around DAR's and reference suppression

---

data-query-tests/src/main/docker/entrypoint.sh
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/Crawler.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/crawler/UsingMagicPatientCrawlerTest.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/crawler/UsingOAuthCrawlerTest.java

Story: https://vasdvp.atlassian.net/browse/ADQ-60
Related PRs:
- https://github.com/department-of-veterans-affairs/health-apis-parent/pull/38
- https://github.com/department-of-veterans-affairs/health-apis-data-query-deployment/pull/29

remove jargonaut support

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderTransformerTest.java

Latest mappings for MedicationOrder.Status as of 09/26/19

new kbs mappings for med order

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/AbstractIncludesIcnMajig.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/Transformers.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceIncludesIcnMajig.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/AbstractIncludesIcnMajigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/TransformersTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceIncludesIcnMajigTest.java

Added AllergyIntolerance patient matching as well as helper functions to extract the patient ICN from a Reference

ADQ-335 AllergyIntolerance patient matching

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationIncludesIcnMajig.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationIncludesIcnMajigTest.java

https://vasdvp.atlassian.net/browse/ADQ-339

Immunization Patient Matching and Test

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationorder/MedicationOrderIncludesIcnMajig.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/MedicationOrderIncludesIcnMajigTest.java

https://vasdvp.atlassian.net/browse/ADQ-342

MedicationOrder Patient Matching Majig and Test

---

data-query/src/main/java/gov/va/api/health/dataquery/service/api/DataQueryService.java

Story: https://vasdvp.atlassian.net/browse/ADQ-317
Related PR: https://github.com/department-of-veterans-affairs/health-apis-fhir-resources/pull/25

add securityrequirement and securityScheme to openapi object

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/PatientBulkFhirIT.java

Rework to IT tests to pass the bulk header using DQ's test client

fixing missing header in IT tests

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureControllerTest.java

https://vasdvp.atlassian.net/browse/SSS-43

SSS-43 RIP Superman

---

data-query-ids-mapping/pom.xml
data-query-tests/pom.xml
data-query/pom.xml
mr-anderson/pom.xml
pom.xml

Application appears to run normally local and inside Docker images.
```
mvn deploy -DskipTests -P'!standard' -Pdocker -Ddocker.skip.push=true -Dmaven.deploy.skip=true -Ddocker.username=$DOCKER_USERNAME -Ddocker.password="$DOCKER_PASSWORD"
docker run --rm -it -v $(pwd)/config/application-docker.properties:/opt/va/application.properties -p 8090:8090  vasdvp/health-apis-data-query:2.0.163-SNAPSHOT
```

Updated to latest version of health-api-parent and Spring 2.2

---

data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/DatamartPatientTest.java

Story: https://vasdvp.atlassian.net/browse/SHANK-29
Tests looked good to me, added two more tests to get complete coverage on the controller.

tests looked good, squeezed last 2 percent

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/Dstu2LocationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/Dstu2LocationMrAndersonTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/Dstu2LocationTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/Dstu2LocationControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/Dstu2LocationMrAndersonControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/Dstu2LocationMrAndersonTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/Dstu2LocationTransformerTest.java

https://vasdvp.atlassian.net/browse/SSS-95
Location renaming
```
DatamartLocationControllerTest  --> Dstu2LocationControllerTest
DatamartLocationTransformer     --> Dstu2LocationTransformer
DatamartLocationTransformerTest --> Dstu2LocationTransformerTest
LocationController              --> Dstu2LocationController
LocationControllerTest          --> Dstu2LocationMrAndersonControllerTest
LocationTransformer             --> Dstu2LocationMrAndersonTransformer
LocationTransformerTest         --> Dstu2LocationMrAndersonTransformerTest
```

Location renaming for Dstu2 prefix

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerController.java

https://vasdvp.atlassian.net/browse/SSS-109

SSS-109 Replace references for practitioner handles missing practitioner role

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java

https://vasdvp.atlassian.net/browse/SSS-112

SSS-112 Integration tests missing practitioners

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java

https://vasdvp.atlassian.net/browse/SSS-113

SSS-113 Add practitioner for production integration tests

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/stu3/PractitionerRoleIT.java

https://vasdvp.atlassian.net/browse/SSS-114

SSS-114 Disable practitioner role integration tests in lab and prod

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/Stu3OrganizationIncludesIcnMajig.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/OrganizationIncludesIcnMajigTest.java

https://vasdvp.atlassian.net/browse/SHANK-266

SHANK-266 Add @ControllerAdvice to Stu3OrganizationIncludesIcnMajig

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerTransformerTest.java

https://vasdvp.atlassian.net/browse/SHANK-267

SHANK-267 Stu3PractitionerTransformer filters null identifiers

---

data-query-tests/pom.xml
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/dstu2/JoshBot.java

https://github.com/department-of-veterans-affairs/health-apis-parent/pull/50

SHANK-000-joshbot-refresh-token

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/Dstu2Transformers.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/ResourceExceptions.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/WebExceptionHandler.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/ConditionEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/datamart/DatamartEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/datamart/DatamartReference.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportsEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/LocationEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medication/MedicationEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationorder/MedicationOrderEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationstatement/MedicationStatementEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/ObservationEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/OrganizationEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientPayloadDto.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureEntity.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/DatamartEntityTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/Dstu2TransformersTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/datamart/DatamartEntityTest.java

https://vasdvp.atlassian.net/browse/SHANK-285

SHANK-285 Handle null payload explicitly

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/DatamartImmunization.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/Dstu2ImmunizationTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/Dstu2ProcedureTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/Dstu2AllergyIntoleranceTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/condition/Dstu2ConditionTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/Dstu2DiagnosticReportTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/immunization/Dstu2ImmunizationTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/Dstu2LocationTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/Stu3LocationTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medication/Dstu2MedicationTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/Dstu2MedicationOrderTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationstatement/Dstu2MedicationStatementTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/observation/Dstu2ObservationTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/Dstu2OrganizationTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/Stu3OrganizationTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/Dstu2PatientTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/procedure/Dstu2ProcedureTransformerTest.java

https://vasdvp.atlassian.net/browse/SHANK-300
(Validation of outgoing FHIR responses in separate PR)

SHANK-300 transformer null pointers

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/ConditionRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/LocationRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medication/MedicationRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationorder/MedicationOrderRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationstatement/MedicationStatementRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/ObservationRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/OrganizationRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientSearchRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureRepository.java

https://www.logicbig.com/tutorials/spring-framework/spring-data/transactions.html
https://docs.spring.io/spring/docs/3.0.x/javadoc-api/org/springframework/transaction/TransactionDefinition.html
https://stackoverflow.com/questions/27198020/what-is-are-difference-between-nolock-and-uncommitted
https://vasdvp.atlassian.net/browse/SHANK-303

add read uncommitted to repositories

---

data-query-ids-mapping/pom.xml
data-query-tests/pom.xml
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/Crawler.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/FileResultsCollector.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/ResourceDiscovery.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/SummarizingResultCollector.java
data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/config/ReferenceSerializerProperties.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/ConfigurableBaseUrlPageLinks.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/DateTimeParameters.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/Dstu2Transformers.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/EnumSearcher.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/IdentityParameterReplacer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/WitnessProtection.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/conformance/MetadataController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/DatamartOrganization.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/DatamartPractitioner.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/validation/DatamartValidationController.java
pom.xml

https://vasdvp.atlassian.net/browse/SHANK-307
Drop SNAPSHOTs after https://github.com/department-of-veterans-affairs/health-apis-parent/pull/54
All code changes correspond to Error Prone findings

SHANK-307 Upgrade to 6.0 parent with Error Prone

---

data-query-ids-mapping/pom.xml
data-query-ids-mapping/src/main/java/gov/va/api/health/dataquery/idsmapping/DataQueryIdsCodebookSupplier.java
data-query-tests/pom.xml
data-query/pom.xml
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/WitnessProtectionTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/Dstu2AllergyIntoleranceControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/appointment/Dstu2AppointmentIncludesIcnMajigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/condition/Dstu2ConditionControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/immunization/Dstu2ImmunizationControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/Dstu2LocationControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/Stu3LocationControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medication/Dstu2MedicationControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationdispense/Dstu2MedicationDispenseIncludesIcnMajigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/Dstu2MedicationOrderControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationstatement/Dstu2MedicationStatementControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/observation/Dstu2ObservationControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/Dstu2OrganizationControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/Stu3OrganizationControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/Dstu2PatientControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/procedure/Dstu2ProcedureControllerTest.java

https://vasdvp.atlassian.net/browse/SHANK-317
Depends on https://github.com/department-of-veterans-affairs/health-apis-ids/pull/16

SHANK-317 Upgrade ID service

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/dstu2/OperationOutcomesAreFunctionallyEqual.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/stu3/OperationOutcomesAreFunctionallyEqual.java

https://vasdvp.atlassian.net/browse/SHANK-329

SHANK-329 OperationOutcomesAreFunctionallyEqual NullPointerException

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java
data-query/src/main/java/gov/va/api/health/dataquery/service/api/DataQueryService.java

also see : https://github.com/department-of-veterans-affairs/health-apis-data-query-deployment/pull/63

Update DQ for sandbox migration

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/OrganizationEntity.java

https://vasdvp.atlassian.net/browse/SHANK-551

SHANK-551-organization-entity-update

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/dstu2/Dstu2OpenApiIT.java
data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/api/Dstu2DataQueryService.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/DataQueryHomeController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/api/DataTypesTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/DataQueryHomeControllerTest.java

https://vajira.max.gov/browse/API-817
Updates dstu2 openapi classes in preparation of r4 openapi.
* Removes dstu2's openapi yaml
* Generates dstu2-openapi.json 
* Makes available `/dstu2-openapi.json` path
* Tests check `$.info.title` to ensure correct fhir spec

Api 817 dstu2 openapi

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/R4OpenApiIT.java
data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/api/R4DataQueryService.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/DataQueryHomeController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/DataQueryHomeControllerTest.java

https://vajira.max.gov/browse/API-818

Api 818 r4 openapi

---

data-query-tests/crawl-localhost
data-query-tests/local-docker-image
data-query-tests/src/main/docker/entrypoint.sh

Can be tested locally by starting DQ and
```
local-docker-image run crawler-test
```
Deployment unit has already been updated to support r4 crawler

API 235 r4 crawler part 3

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/ConditionIT.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionControllerTest.java

https://vajira.max.gov/browse/API-997

Api 997 remove systemcode logic

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestFromMedicationStatementTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationrequest/MedicationRequestSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestFromMedicationStatementTransformerTest.java

https://vajira.max.gov/browse/API-1211 
Added Transformer for MedicationRequest.
Added /R4MedicationRequestFromMedicationStatementTransformer, unit test, and updated the MedicationRequestSample.

MedicationRequest Transformer From MedicationStatement

---

data-query/pom.xml

https://vajira.max.gov/browse/API-1244

API-1244 Upgrade guava

---

data-query-tests/src/main/docker/entrypoint.sh

[API-1232](https://vajira.max.gov/browse/API-1232)

API-1232-ITs-exercise-fhir-v0

---

data-query/src/test/java/gov/va/api/health/dataquery/service/api/DataTypesTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/config/Dstu2JacksonMapperTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/config/JaxbRestTemplateConfigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/config/R4JacksonMapperTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/config/ReferenceSerializerPropertiesTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/config/Stu3JacksonMapperTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/ConfigurableBaseUrlPageLinksDstu2Test.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/ConfigurableBaseUrlPageLinksR4Test.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/ConfigurableBaseUrlPageLinksStu3Test.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/CountParameterResolverTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/DataQueryHomeControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/DateTimeParameterValidatorTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/Dstu2BundlerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/Dstu2TransformersTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/EnumSearcherTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/IncludesIcnMajigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/PageAndCountValidatorTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/ParametersTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/R4TransformersTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/ResourceNameTranslationTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/Stu3TransformersTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/TransformersTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/ValidationAdviceTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/WebExceptionHandlerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/WitnessProtectionTest.java

[API-1303](https://vajira.max.gov/browse/API-1303)
Updates methods that do not directly correlate to a fhir controller.

API-1303-junit5-helpers

---

data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/R4AllergyIntoleranceControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/R4AllergyIntoleranceTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/immunization/R4ImmunizationControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medication/R4MedicationControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medication/R4MedicationTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationrequest/MedicationRequestIncludesIcnMajigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestFromMedicationOrderTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/metadata/R4MetadataControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/GenderMappingTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/PatientBulkFhirControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/PatientIncludesIcnMajigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureIncludesIcnMajigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/procedure/R4ProcedureControllerTest.java

https://vajira.max.gov/browse/API-1301

Api 1301 junit5 r4

---

data-query-tests/src/main/docker/entrypoint.sh

Should solve both issues seen in the lab deployment this morning.

API-1232-fhirv0-support

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/TestIds.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/IdentityServiceIT.java

https://vajira.max.gov/browse/API-1414

Api 1414 ids it

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/ObservationIT.java
data-query/spotbugs-excludes.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/ObservationRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationControllerTest.java

[API-1219](https://vajira.max.gov/browse/API-1219)

Api 1219 observation category token search

---

data-query/spotbugs-excludes.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DatamartDiagnosticReport.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportEntity.java

https://vajira.max.gov/browse/API-1456
See https://github.com/department-of-veterans-affairs/health-apis-datamart-synthetic-records/pull/38

API-1464 Diagnostic report V2 model

---

data-query-ids-mapping/pom.xml
data-query-tests/pom.xml
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/ReferenceInterceptor.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/SummarizingResultCollector.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/crawler/UrlToResourceConverter.java
data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/ConfigurableBaseUrlPageLinks.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/IdentityParameterReplacer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/ResourceExceptions.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/ResourceNameTranslation.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/Transformers.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medication/Dstu2MedicationController.java
pom.xml

[API-1603](https://vajira.max.gov/browse/API-1603)

Api 1603 error prone fixes

---

data-query-ids-mapping/pom.xml
data-query-tests/pom.xml
data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/Dstu2DiagnosticReportController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/Dstu2DiagnosticReportTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/R4DiagnosticReportTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/Dstu2DiagnosticReportControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/Dstu2DiagnosticReportTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/R4DiagnosticReportTransformerTest.java
pom.xml

[API-1628](https://vajira.max.gov/browse/API-1628)

Api 1628 lab search ch mb

---

data-query-tests/local-docker-image
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/DiagnosticReportIT.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/R4DiagnosticReportController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/R4MetadataController.java
data-query/src/test/resources/patient-r4-capability.json

[API-1666](https://vajira.max.gov/browse/API-1666)

Api 1666 it and crawler

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/DiagnosticReportIT.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/Dstu2DiagnosticReportController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/R4DiagnosticReportController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/R4DiagnosticReportControllerTest.java

https://vajira.max.gov/browse/API-1640

Api 1640 token searching

---

data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/api/Dstu2DataQueryService.java
data-query/src/main/java/gov/va/api/health/dataquery/service/api/R4DataQueryService.java

Waiting on https://github.com/department-of-veterans-affairs/health-apis-fhir-resources/pull/81

Api 2200 verify r4 swag

---

data-query/src/main/java/gov/va/api/health/dataquery/service/api/R4DataQueryService.java

I tested the Swagger [here](https://editor.swagger.io/) and it created the hyperlink.

API-2217-swagger-description-text

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/OrganizationRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/R4OrganizationController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/OrganizationRepositoryTest.java

https://vajira.max.gov/browse/API-2121
Enhanced searching by address.

R4 Organization: Enhanced searchByAddress

---

data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/PractitionerRoleSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleTransformerTest.java

Api 2974 r4 practitioner role

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/device/DatamartDevice.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/device/DeviceEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/device/DeviceRepository.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/device/DatamartDeviceTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/device/DeviceSamples.java
data-query/src/test/resources/gov/va/api/health/dataquery/service/controller/device/datamart-device-v1.json
data-query/src/test/resources/gov/va/api/health/dataquery/service/controller/device/datamart-device.json

API-3430-datamart-device

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/device/DatamartDevice.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/device/R4DeviceTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/device/DeviceSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/device/R4DeviceTransformerTest.java

API-03428-device-transformer

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/DeviceIT.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/device/R4DeviceController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/device/R4DeviceControllerTest.java

API-3520-device-search-by-type

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerTransformerTest.java

API-2972-identifier-unknown

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/Dstu2ObservationTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/observation/Dstu2ObservationTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationTransformerTest.java

API-3191-interpretation-display

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PatientIT.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/DatamartPatient.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/Dstu2PatientTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/vulcanizer/VulcanizedBundler.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/vulcanizer/VulcanizedTransformation.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/PatientSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientControllerTest.java

API-3093-update-patient-search

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientEntityV2.java

API-4128-add-columns-to-entity

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/TestIds.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PatientIT.java
data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientEntityV2.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientControllerTest.java

API-4130-ssn-field-controller-additions

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/ConditionIT.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/condition/ConditionSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionControllerTest.java

API-3085-condition-search-capabilities

---

data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/DateTimeParameters.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/JpaDateTimeParameter.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/DiagnosticReportRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/ObservationRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientRepositoryV2.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureRepository.java

~update to non snapshot after https://github.com/department-of-veterans-affairs/health-apis-fhir-resources/pull/119 merges~ :heavy_check_mark:

Api 5165 move date time parameter logic

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/R4Transformers.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/R4LocationTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/R4OrganizationTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/R4TransformersTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/LocationSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/R4LocationTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/R4OrganizationTransformerTest.java
src/scripts/make-configs.sh

Populate location identifier for facility ID, using same logic as Organization
```
curl -s 'http://localhost:8090/r4/Location/I2-7Q2IQADBCYM2BLJFCUUND7ITEE000000'
{
"resourceType": "Location",
"id": "I2-7Q2IQADBCYM2BLJFCUUND7ITEE000000",
"identifier": [{
"use": "usual",
"type": {
"coding": [{
"system": "http://terminology.hl7.org/CodeSystem/v2-0203",
"code": "FI",
"display": "Facility ID"
}
],
"text": "Facility ID"
},
"system": "https://api.va.gov/services/fhir/v0/r4/NamingSystem/va-facility-identifier",
"value": "vha_688"
}
],
"status": "active",
"name": "MENTAL HEALTH SERVICES",
"description": "MENTAL HEALTH SERVICES",
"mode": "instance",
"type": [{
"coding": [{
"display": "PSYCHIATRY CLINIC"
}
],
"text": "PSYCHIATRY CLINIC"
}
],
"telecom": [{
"system": "phone",
"value": "202-745-8267" …
```

API-5661 location facility identifier

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/FacilityTransformers.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/R4Transformers.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/R4LocationTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/R4OrganizationTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/FacilityTransformersTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/R4TransformersTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/LocationSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/R4LocationTransformerTest.java

Populate location identifier for clinic ID
```
$ curl -s 'http://localhost:8090/r4/Location/I2-7Q2IQADBCYM2BLJFCUUND7ITEE000000'
{
"resourceType": "Location",
"id": "I2-7Q2IQADBCYM2BLJFCUUND7ITEE000000",
"identifier": [{
"use": "usual",
"type": {
"coding": [{
"system": "http://terminology.hl7.org/CodeSystem/v2-0203",
"code": "FI",
"display": "Facility ID"
}
],
"text": "Facility ID"
},
"system": "https://api.va.gov/services/fhir/v0/r4/NamingSystem/va-facility-identifier",
"value": "vha_688"
}, {
"system": "https://api.va.gov/services/fhir/v0/r4/NamingSystem/va-clinic-identifier",
"value": "vha_688_3485"
}
],
"status": "active",
"name": "MENTAL HEALTH SERVICES",
"description": "MENTAL HEALTH SERVICES",
"mode": "instance",
"type": [{
"coding": [{
"display": "PSYCHIATRY CLINIC"
}
],
"text": …
```

API-5662 location clinic identifier

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PractitionerIT.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/stu3/PractitionerIT.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/stu3/PractitionerRoleIT.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerControllerTest.java

API-5856-read-by-npi

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/OrganizationEntity.java

API-6141-update-org-entity

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/OrganizationIT.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/R4OrganizationController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/OrganizationSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/R4OrganizationControllerTest.java

API-6145-vulcanize-organization

---

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/OrganizationIT.java

API-000-org-local-only

---

data-query-patient-registration/pom.xml
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/TestIds.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/OrganizationIT.java
data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/FacilityId.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/FacilityTransformers.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/device/R4DeviceController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/R4OrganizationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/R4OrganizationControllerTest.java

I've reved the pom to what will be the new vulcan version. Once that merges, a rebuild of this branch should yield a success. After that, it can be placed in ready to review.

API-6143-search-identifier-by-fapi-id

---

data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/config/PathRewriteConfig.java

This PR can be merged on it's own, but moving the rewrite will require ingress and kong changes before the talos configuration actually takes effect.

API-6243-path-rewrite

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java

API-000-lab-org-it-fix

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/DatamartAppointment.java

https://vajira.max.gov/browse/API-6684

API-6684 add visitSid to appointment datamart model

---

data-query/src/main/java/gov/va/api/health/dataquery/service/api/Dstu2DataQueryService.java
data-query/src/main/java/gov/va/api/health/dataquery/service/api/R4DataQueryService.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/R4AllergyIntoleranceController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/R4AllergyIntoleranceControllerTest.java

API-3084-vulcan-all-int

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/MedicationOrderSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationstatement/MedicationStatementSamples.java

This PR contains updates to vulcanize the read operations of MedicationRequest. Due to the complexity of the MedicationRequest controller and in order to prevent a large PR, updated searching will come separately

Api 3089 vulcanize med request

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/DatamartAppointment.java

https://vajira.max.gov/browse/API-5305

API-5305 add lastUpdated to DatamartAppointment

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/appointment/AppointmentSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformerTest.java
data-query/src/test/resources/gov/va/api/health/dataquery/service/controller/appointment/datamart-appointment.json

https://vajira.max.gov/browse/API-6924
[synthetic records PR](https://github.com/department-of-veterans-affairs/health-apis-datamart-synthetic-records/pull/140)

API-6924 populate appointment lastUpdated

---

data-query-ids-mapping/pom.xml
data-query-patient-registration/pom.xml
data-query-tests/pom.xml
data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/config/PathRewriteConfig.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/R4AllergyIntoleranceController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/device/R4DeviceController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/R4DiagnosticReportController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/R4ImmunizationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/R4LocationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/R4OrganizationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/R4ProcedureController.java
data-query/src/main/resources/application.properties
src/scripts/make-configs.sh

API-7181-upgrade-dependencies

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/Dstu2ConditionTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/condition/ConditionSamples.java

Updated the ICD-10 system per Jay's recommendation. The ICD-9 system was already using the CM url.

API-7550-icd-system-correction

---

data-query/pom.xml
data-query/src/main/java/gov/va/api/health/dataquery/service/config/LinkProperties.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/R4AllergyIntoleranceController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/device/R4DeviceController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/R4DiagnosticReportController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/R4ImmunizationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/R4LocationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/R4OrganizationController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/R4ProcedureController.java

https://vajira.max.gov/browse/API-7729
Add support for `Appointment?_sort=date`
[Vulcan PR](https://github.com/department-of-veterans-affairs/lighthouse-vulcan/pull/21)
[Swagger](https://github.com/department-of-veterans-affairs/health-apis-fhir-resources/pull/127)

API-7729 appointment sort by date

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerIncludesIcnMajigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/PractitionerRoleIncludesIcnMajigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/PractitionerRoleSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleTransformerTest.java

Reverts department-of-veterans-affairs/health-apis-data-query#751
See https://libertyits.slack.com/archives/C014R5Y1RDX/p1623447417199800

Revert "API-7883 use CompositeCdwId for Practioner and PractitionerRole"

---

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java
data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PractitionerIT.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/CompositeCdwIds.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerRepository.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleTransformer.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleController.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleTransformer.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerIncludesIcnMajigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/PractitionerRoleIncludesIcnMajigTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/PractitionerRoleSamples.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleTransformerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleControllerTest.java
data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleTransformerTest.java

This is the do-over for https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/751 that was reverted (see https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/752 and https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/753)

API-8010 use composite ID for practitioner and practitioner-role

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/PractitionerRoleSpecialtyMapEntity.java
data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/SpecialtyMapCompositeId.java

Follow up PR to synthetic datamart will use the entity to populate synthetic data.

API-8341: practitioner role specialty mapping entity

---

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerEntity.java

see also [datamart-synthetic-records](https://github.com/department-of-veterans-affairs/health-apis-datamart-synthetic-records/pull/164)

API-8573 remove PractitionerEntity cdwId

---

data-query-tests/src/main/docker/entrypoint.sh
data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java

API-000-option-port-sentinel
