pom.xml, service-starter/pom.xml
This includes using update base image and application image names.
=> Updated docker image build to use `vasdvp` on Dockerhub

.git-secrets-patterns, .gitallowed, ids/run-local.sh, ids/src/main/resources/application.properties, service-starter/pom.xml
- Updates secrets to discover spring passwords when used in scripts
- Updates to allowed patterns so that variables can be used, e.g. `password=$WOW_SECRET`
- H2 database library is automatically added to the target directory for easy access
- `run-local.sh` test script for launching `ids` using an ephemeral H2 database
=> Task/api 86 H2 configuration for testing with temporary databases

service-auto-config/src/main/java/gov/va/api/health/autoconfig/configuration/SecureRestTemplateConfig.java, service-auto-config/src/main/java/gov/va/api/health/autoconfig/configuration/SslClientProperties.java, service-auto-config/src/test/java/gov/va/api/health/autoconfig/configuration/SecureRestTemplateConfigTest.java
This is needed to be able to test the application in some environments. Uses, 'ssl.verify=false' property
=> Add support to disable hostname verification in the rest client. 

pom.xml, src/scripts/trust-dev-certs.sh
- Now replaces previously trusted `internal-sys-dev` instead of failing if it already exists.
=> trust-dev-certs.sh

argonaut/src/main/java/gov/va/api/health/argonaut/service/healthcheck/SteelThreadSystemCheck.java, argonaut/src/main/resources/application.properties, argonaut/src/test/java/gov/va/api/health/argonaut/service/healthcheck/SteelThreadHealthCheckTest.java, sentinel/pom.xml, sentinel/src/main/java/gov/va/health/api/sentinel/FhirTestClient.java, sentinel/src/test/java/gov/va/health/api/sentinel/HealthCheckIT.java, src/scripts/make-configs.sh
Fixes health checks preventing applications for starting with Sentinel.
Changes
- Renamed `health.id` to `health-check.medication-id` to more clearly describe what it is
- `health-check.medication-id` supports the value `skip` to skip the interacting with downstream services
- Update `make-configs` to set `health-check.medication-id` to a value usable with Sandbox
- Sentinel now explicitly skips steel thread health checks
- Steel thread health check now properly catches HTTP client exceptions and reports
service as `DOWN` instead of returning a `404` and an OperationOutcome
=> Health check fixes

argonaut/src/main/java/gov/va/api/health/argonaut/service/config/ArgonautJacksonMapper.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/ConfigurableBaseUrlPageLinks.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/allergyintolerance/AllergyIntoleranceController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/condition/ConditionController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/diagnosticreport/DiagnosticReportController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/encounter/EncounterController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/immunization/ImmunizationController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medication/MedicationController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/observation/ObservationController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/patient/PatientController.java, argonaut/src/main/resources/application.properties, argonaut/src/test/java/gov/va/api/health/argonaut/service/config/ArgonautJacksonMapperTest.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/ConfigurableBaseUrlPageLinksTest.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/allergyintolerance/AllergyIntoleranceControllerTest.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/condition/ConditionControllerTest.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/diagnosticreport/DiagnosticReportControllerTest.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/encounter/EncounterControllerTest.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/immunization/ImmunizationControllerTest.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/medication/MedicationControllerTest.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/observation/ObservationControllerTest.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/observation/ObservationTransformerTest.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/patient/PatientControllerTest.java, service-auto-config/src/main/java/gov/va/api/health/autoconfig/configuration/JacksonConfig.java
- Adds new Jackson ObjectMapper constomizations that will fully qualify references during serialization.
- Adds new `argonaut.base-path` configurable to account for lab environment where base path isn't `api`
- Changes the way bundle links are created such that they no longer take the full request URI, but rather just the resource name.
=> Argonaut fully qualified reference links

argonaut/src/main/java/gov/va/api/health/argonaut/service/config/ArgonautJacksonMapper.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/practitioner/PractitionerController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/practitioner/PractitionerTransformer.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/practitioner/PractitionerControllerTest.java, argonaut/src/test/java/gov/va/api/health/argonaut/service/controller/practitioner/PractitionerTransformerTest.java, argonaut/src/test/resources/cdw/old-practitioner-1.00.json, sentinel/src/main/java/gov/va/health/api/sentinel/IdRegistrar.java, sentinel/src/main/java/gov/va/health/api/sentinel/SystemDefinitions.java, sentinel/src/main/java/gov/va/health/api/sentinel/TestIds.java, sentinel/src/test/java/gov/va/health/api/sentinel/ArgonautReadAndSearchIT.java, sentinel/src/test/java/gov/va/health/api/sentinel/ArgonautValidateIT.java
Add Practitioner support for read, search by _id and identifier, validate, and add the appropriate sentinel tests.
Related story: https://vasdvp.atlassian.net/browse/API-430
=> Task/API 430 Practitioner Read Search Validate Sentinel

argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/conformance/MetadataController.java, argonaut/src/test/resources/old-conformance.json
The Jargonaut Smart-On-Fhir documentation has been updated from http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris to http://www.hl7.org/fhir/smart-app-launch/index.html. This change needs to be reflected in the conformance statement.
Related story: https://vasdvp.atlassian.net/browse/API-604
=> task/API-604 Update the Jargonaut Smart-On-Fhir documentation link in conformance

sentinel/src/main/java/gov/va/health/api/sentinel/Sentinel.java, sentinel/src/test/java/gov/va/health/api/sentinel/PatientIT.java
Added logic around the unknown patient search test to handle when patient validation is on or off.
403 forbidden in qa/prod
404 not found in local ie... sandbox
=> Added env parsing to sentinel. Refactored patient read test to be smrter

argonaut-api/src/main/java/gov/va/api/health/argonaut/api/resources/Practitioner.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/config/ArgonautJacksonMapper.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/config/MagicReferenceConfig.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/allergyintolerance/AllergyIntoleranceController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/appointment/AppointmentController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/condition/ConditionController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/conformance/MetadataController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/diagnosticreport/DiagnosticReportController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/encounter/EncounterController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/immunization/ImmunizationController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/location/LocationController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medication/MedicationController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medicationorder/MedicationOrderController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/medicationstatement/MedicationStatementController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/observation/ObservationController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/organization/OrganizationController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/patient/PatientController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/practitioner/PractitionerController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/controller/procedure/ProcedureController.java, argonaut/src/main/java/gov/va/api/health/argonaut/service/mranderson/client/RestMrAndersonClient.java, mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/impl/IdentityParameterReplacer.java, mr-anderson/src/main/java/gov/va/api/health/mranderson/cdw/impl/WitnessProtectionResources.java, pom.xml, sentinel/src/main/java/gov/va/health/api/sentinel/ExpectedResponse.java, sentinel/src/main/java/gov/va/health/api/sentinel/FhirTestClient.java, sentinel/src/main/java/gov/va/health/api/sentinel/ServiceDefinition.java, sentinel/src/main/java/gov/va/health/api/sentinel/SystemDefinition.java, sentinel/src/main/java/gov/va/health/api/sentinel/crawler/Crawler.java, service-auto-config/src/main/java/gov/va/api/health/autoconfig/configuration/JacksonConfig.java
Enable `javac` compiler warnings and make them fail the build. Only main source files are analzyed, not test code.
The `serial` warning, which warns about missing `serialVersionUID` definitions on serializable classes, is suppressed. 
The `processing` warning is also suppressed. Those warnings looks like this:
```
[WARNING] No processor claimed any of these annotations:
org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean,
org.springframework.beans.factory.annotation.Autowired,
org.springframework.boot.context.properties.ConfigurationProperties,
org.springframework.context.annotation.Configuration,
org.springframework.boot.context.properties.EnableConfigurationProperties,
org.springframework.context.annotation.Bean
```
These warnings are caused by Lombok's annotation …
=> API-712 fail health-apis build on compiler warnings

sentinel/src/test/java/gov/va/health/api/sentinel/ResourceVerifier.java, sentinel/src/test/resources/logback-test.xml
```
2019-01-24 22:18:51 INFO  g.v.h.api.sentinel.ResourceVerifier - Verify /api/Patient?family={family}&gender={gender} with [VETERAN, male] page bounds
2019-01-24 22:18:52 INFO  g.v.h.api.sentinel.ResourceVerifier - Verify /api/Patient?family={family}&gender={gender} with [VETERAN, male] is Bundle (200)
2019-01-24 22:18:53 INFO  g.v.h.api.sentinel.ResourceVerifier - Verify /api/Patient?given={given}&gender={gender} with [JOHN Q, male] page bounds
2019-01-24 22:18:54 INFO  g.v.h.api.sentinel.ResourceVerifier - Verify /api/Patient?given={given}&gender={gender} with [JOHN Q, male] is Bundle (200)
```
instead of `Testing 3 cases`
Also suppressed Hibernate Validator spam.
=> Updated logging of sentinel tests to look like this:

sentinel/src/test/java/gov/va/health/api/sentinel/CdwCrawlerTest.java, sentinel/src/test/java/gov/va/health/api/sentinel/LabCrawlerTest.java, sentinel/src/test/java/gov/va/health/api/sentinel/StagingCrawlerTest.java, sentinel/src/test/java/gov/va/health/api/sentinel/Swiggity.java
- CdwCrawler has been updated to support optional link url overrides
- Swiggity Swooty has been extracted from the three crawlers into one
The following example shows running the crawler against an alternative URL replacing original URL links
```
docker run --rm -it vasdvp/health-apis-sentinel:bs test gov.va.health.api.sentinel.CdwCrawlerTest \
-Daccess-token=$TOKEN \
-Dsentinel=QA \
-Dsentinel.argona.url=https://green.freedomstream.io  \
-Dsentinel.argonaut.url.replace=https://qa-argonaut.lighthouse.va.gov
```
=> Crawler support for blue/green environments

sentinel/src/main/java/gov/va/health/api/sentinel/SystemDefinitions.java
Related story: https://vasdvp.atlassian.net/browse/API-883
Removed trailing slashes from basepaths if present, as API paths will always have preceding slashes.
=> remove trailing slash if present from basepaths

sentinel/src/main/java/gov/va/health/api/sentinel/crawler/UrlReplacementRequestQueue.java, sentinel/src/test/java/gov/va/health/api/sentinel/crawler/UrlReplacementRequestQueueTest.java
Make /'s agnostic in sentinel crawlers to prevent missing or double /'s in url replacement.
=> Task/API-882 Edit url replacement request queue builder to be agnostic about /s

data-query-api/src/main/java/gov/va/api/health/dataquery/api/elements/Extension.java, data-query-api/src/test/java/gov/va/api/health/dataquery/api/AbstractRelatedFieldVerifier.java, data-query-api/src/test/java/gov/va/api/health/dataquery/api/samples/SampleDataTypes.java
JIRA Link: https://vasdvp.atlassian.net/browse/ADQ-2
`Extension.java` has been updated to include missing fields and to remove duplicate fields.
`AbstractRelatedFieldVerifier.java` and `SampleDataTypes.java` were updated to verify the added fields to `Extension.java`.
=> Task/ADQ-2 missing Extension element fields

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/ConfigurableBaseUrlPageLinks.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/ConfigurableBaseUrlPageLinksTest.java
See https://www.hl7.org/fhir/search.html#count
> if _count has the value 0, this shall be treated the same as _summary=count: the server returns a bundle that reports the total number of resources that match in Bundle.total, but with no entries, and no prev/next/last links.
Links look like this now
```
$ curl -HDatamart:true -sH"$A" "http://localhost:8090/DiagnosticReport?patient=111222333V000999&_count=0" | jq .
{
"resourceType": "Bundle",
"type": "searchset",
"total": 63,
"link": [
{
"relation": "self",
"url": "http://localhost:8090/api/DiagnosticReport?patient=111222333V000999&page=1&_count=0"
}
],
"entry": []
}
```
=> Fixes page links when count = 0 to just include 'self' link

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceController.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/AllergyIntoleranceEntity.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/ConditionController.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/ConditionEntity.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationController.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationEntity.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationstatement/MedicationStatementController.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationstatement/MedicationStatementEntity.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureController.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/ProcedureEntity.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/DatamartAllergyIntoleranceControllerTest.java
This is solving the issue where the same request can have slightly different results:
```
$ curl -sH"$A" -HDatamart:true "https://api.va.gov/services/fhir/v0/dstu2/Immunization?patient=1011537977V693883" | jq -r '.entry[].fullUrl'
https://api.va.gov/services/fhir/v0/dstu2/Immunization/00f4000a-b1c9-5190-993a-644569d2722b
https://api.va.gov/services/fhir/v0/dstu2/Immunization/af5b4cbc-8bc0-59c8-b027-baa78f5c7f59
https://api.va.gov/services/fhir/v0/dstu2/Immunization/1b476df4-429f-53a8-94ec-7521cc3579a9
https://api.va.gov/services/fhir/v0/dstu2/Immunization/a1c8f77b-35f5-53d5-9004-f30425cf8117
https://api.va.gov/services/fhir/v0/dstu2/Immunization/2d65782a-171b-56ed-b265-9a4bcd4c1b98
https://api.va.gov/services/fhir/v0/dstu2/Immunization/3c009e39-7960-56d6-8597-fb1f9d169360
$ curl -sH"$A" …
```
=> Added natural ordering to entities and sorting to AI, Cond, Imm, MedSt and Proc

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderTransformer.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderSamples.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderTransformerTest.java
New medication orders with system and code:
{
"resourceType": "MedicationOrder",
"id": "5d09da19-5f8c-5549-ac70-5c9b865f5d40",
"dateWritten": "2015-01-15T21:09:41Z",
"status": "completed",
"patient": {
"reference": "http://localhost:8090/api/Patient/111222333V000999",
"display": "Olson653, Conrad619"
},
"_prescriber": {
"extension": [
{
"url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
"valueCode": "unsupported"
}
]
},
"medicationReference": {
"reference": "http://localhost:8090/api/Medication/0c65178b-0765-5550-a5fc-11955b6bee24",
"display": "ALBUTEROL 90MCG (CFC-F) 200D ORAL INHL"
},
"dosageInstruction": [
{
"text": "USE 2 PUFFS BY MOUTH 4 TIMES PER DAY AS NEEDED FOR BREATHING",
"timing": {
"code": {
"text": "QID PRN"
}
},
"asNeededBoolean": true,
"route": {
"text": …
=> fix missing mo fields

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medication/DatamartMedicationTransformer.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medication/DatamartMedicationSamples.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medication/DatamartMedicationTransformerTest.java
under certain situations.
This change updates the coding such that
1. If rxnorm information is available, return it as the code.
2. If rxnorm is not available, but product is, then this is a "local" drug. We will use the
local drug name as the text and the code.coding.display value. The product.id is the VA
specific "VUID" medication ID. We want to use this value as the code.coding.code along with the
VA specific system.
3. If neither rxnorm or product is available, we'll create a code with no coding, using just
the local drug name as text.
=> The KBS guidelines are unclear as the coding value of Medication 

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrder.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderTransformer.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderSamples.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderTest.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderTransformerTest.java, data-query/src/test/java/gov/va/api/health/dataquery/tools/minimart/transformers/F2DMedicationOrderTransformer.java, data-query/src/test/resources/gov/va/api/health/dataquery/service/controller/medicationorder/datamart-medication-order.json
MedicationOrder now supports Datamart status values in both the current FHIR-style enumeration values and the future VistA enumeration values. New VistA values are mapped to FHIR values, e.g. DISCONTINUED -> stopped
https://libertyits.slack.com/files/U81B5TXEW/FN8R4B65R/argo1_medicationorderstatusv1.docx
=> MedicationOrder.status VistA value support

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderTransformer.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderSamples.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationorder/DatamartMedicationOrderTransformerTest.java
Conversation:
https://libertyits.slack.com/archives/GNKFNQ5FE/p1569351705061200
Snippet from KBS mapping guidelines
```
'DC' FOR DISCONTINUED;    stopped
'DE' FOR DISCONTINUED (EDIT);    stopped
'HD' FOR HOLD;    on-hold
'RNW' FOR RENEW;    active
'RF' FOR REFILL REQUEST;    active
'NW' FOR NEW ORDER;    draft
0' FOR ACTIVE;     active
12' FOR DISCONTINUED;      stopped
'1' FOR NON-VERIFIED;    draft
'15' FOR DISCONTINUED (EDIT);    stopped
11' FOR EXPIRED;     completed
3' FOR HOLD;     on-hold
'10' FOR DONE;    <not used>
'2' FOR REFILL;    <not used>
'4' FOR DRUG INTERACTIONS;    draft
5' FOR SUSPENDED;     on-hold
'13' FOR DELETED;    entered-in-error
'14' FOR DISCONTINUED BY PROVIDER;    stopped
'16' FOR PROVIDER HOLD;    on-hold
A' FOR ACTIVE    active
D' FOR DISCONTINUED    stopped …
```
=> Medication Order status field mappings to match the latest KBS guidelines

data-query/src/test/java/gov/va/api/health/dataquery/tools/minimart/transformers/F2DPatientTransformer.java
https://vasdvp.atlassian.net/browse/ADQ-278
Story says to map into fhir, but there is no field to represent this data, and we dont care about this field.
Using the fhir text to populate the datamart relationship field since it is non-optional.
=> Fhir to datamart: Populate datamart relationship with fhir text field

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/PatientBulkFhirIT.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientBulkFhirController.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientPayloadDto.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientRepository.java
* Created PatientPayloadDto for JPA projection
* Updated the PatientRepository to have a method to get the projected data. 
* Added an Integration test to repeatedly ask for data to evaluate performance of the endpoint.
*  Performance stats running this IT asking for 84 patients 100 times in a row
* Without this change: Average ~14.5 seconds
* With this change: Average ~11.5 seconds
* Thats about a 20% improvement
=> SHANK-139 Performance Tuning for bulk Patient endpoint

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/Dstu2ObservationController.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/observation/Dstu2ObservationControllerTest.java
Alters behavior of Observation.searchByPatientAndCategory to select all records and paginate in application code per Andrew Kelly's recommendation since SQL Server is performing a full table scan when paging criteria is part of the query.
This solution makes me sad.
It is enabled by default, but can be disabled per request with HTTP request header query-hack:false
=> Observation query hack to select all records and paginate in application code

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/ValidationAdvice.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/ValidationAdviceTest.java
https://vasdvp.atlassian.net/browse/SHANK-301
Example messages:
```
WARN 21648 --- [nio-8090-exec-3] g.v.a.h.d.s.controller.ValidationAdvice  : read() response gov.va.api.health.stu3.api.resources.Practitioner failed validation: resourceType must not be blank, name.family must not be null, id must match "[A-Za-z0-9\-\.]{1,64}"
WARN 21648 --- [nio-8090-exec-2] g.v.a.h.d.s.controller.ValidationAdvice  : searchById(_id=[416704]) response gov.va.api.health.stu3.api.resources.Practitioner$Bundle failed validation: entry[0].resource.name.family must not be null, entry[0].resource.resourceType must not be blank, entry[0].resource.id must match "[A-Za-z0-9\-\.]{1,64}"
```
=> SHANK-301 Validate FHIR responses

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientCombinedEntity.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientEntityV2.java
New Patient entity model for the combined tables approach
PR for the entity alone first, so that I can populate the Synthetic DB with our new Patient Table using MitreMinimartMaker tooling.
See: https://github.com/department-of-veterans-affairs/health-apis-datamart-synthetic-records/pull/24
=> New Patient entity model

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/dstu2/PatientIT.java, data-query/spotbugs-excludes.xml, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/Dstu2PatientController.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/PatientRepositoryV2.java, data-query/src/main/resources/application.properties, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/WebExceptionHandlerTest.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/DatamartPatientTest.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/Dstu2PatientControllerTest.java
*****DO NOT MERGE: DU CHANGES REQUIRED FIRST*****
Change to support PatientEntityV2 and PatientEntity + PatientSearchEntity simultaneously via a feature toggle. 
Feature toggle header is in place, defaults to false `-HpatientV2: true`
To test this, you will need the new local DQDB seen here:
https://github.com/department-of-veterans-affairs/health-apis-datamart-synthetic-records/pull/25
=> patient v2 with feature toggle

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/WebExceptionHandler.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/WebExceptionHandlerTest.java
`$  curl -v -X PUT "http://localhost:8090/r4/AllergyIntolerance?patient=1011537977V69388"`
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8090 (#0)
> PUT /r4/AllergyIntolerance?patient=1011537977V69388 HTTP/1.1
> Host: localhost:8090
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 405 
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Fri, 19 Jun 2020 14:29:04 GMT
< 
* Connection #0 to host localhost left intact
```
`{"id":"125fab34-cb00-4af0-864a-f06ac4fa126d","resourceType":"OperationOutcome","text":{"status":"additional","div":"<div>Failure: /r4/AllergyIntolerance</div>"},"extension":[{"url":"timestamp","valueInstant":"2020-06-19T14:29:04.663765Z"},{"url":"type","valueString":"HttpRequestMethodNotSupportedException"},{"u …
=> DQ can return 405 not allowed

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/ResourceVerifier.java
The loinc codes use numbers for their values (i.e. `{loinc1}`) this fixes the substitution for those codes.
=> API-1271-fix-regex

data-query-tests/.gitignore, data-query-tests/lab-login
- lab-login now supports user IDs in addition to emails.
- lab-login now generates a lab-user.conf file that can be sourced for easier scripting. It contains LAB_EMAIL, LAB_USER, and LAB_TOKEN variables
Usage
```
$ lab-login 17 && . lab-user.conf
curl -sH"Authorization: Bearer $LAB_TOKEN" https://sandbox-api.va.gov/services/fhir/v0/r4/Patient/$LAB_USER
```
=> API 2164 oauth v1 support

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/DataQueryScopes.java
https://vajira.max.gov/browse/API-3242 
All scopes listed couldnt be added at this time, but MedicationRequest could.
Talks are ongoing about adding the others to the authentication server.
=> add MedicationRequest scope

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/Dstu2ObservationController.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationController.java
"The Observation_LabChem PostProcessing has completed. You should be good to remove the work around code".
=> remove workaround for duplicate observation records

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/etlstatus/LatestResourceEtlStatusController.java
Decreasing time to allow alert to return during the day for data sources team to react more efficiently.
=> Decreased tooLongAgo from 36 to 28

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/AllergyIntoleranceIT.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/R4AllergyIntoleranceController.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/R4AllergyIntoleranceControllerTest.java
This updates the patient search functionality to be a reference instead of value. The search by patient and code functionality was pushed out of this task and into another because code is not a searchable column in the database.
=> API-3084-update-search-capabilities

data-query/pom.xml, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionController.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/R4DiagnosticReportController.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationController.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/diagnosticreport/R4DiagnosticReportControllerTest.java
In support of https://github.com/department-of-veterans-affairs/lighthouse-vulcan/pull/14 , this PR updates the deprecated tokenCsvList mappings in data-query.
=> API-6945-update-token-mappings

data-query-tests/pom.xml, data-query-tests/src/main/docker/entrypoint.sh, data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/StaticRefreshIT.java
Uses the refreshUserAccessToken method in health-apis-parent to perform a static refresh for both the dstu2 and r4 token endpoints.
=> API-7137-static-refresh-it

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/appointment/AppointmentSamples.java
This PR updates the R4 `Appointment.appointmentType` system value being emitted to use the VistA-specific identifier.
=> API-5012: update appointmentType system value

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PractitionerIT.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerController.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerControllerTest.java
Adds identifier search support to R4 Practitioner Controller. Supports `npi` and `I2` searches.
=> Add identifier search to R4 Practitioner

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PractitionerIT.java
Temporarily disable Practitioner identifier search ITs in lower environments until indexing solution is worked out.
=> API-3444 move all practitioner identifier search ITs to LOCAL only

data-query-tests/pom.xml, data-query/pom.xml, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/Stu3LocationTransformer.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/organization/Stu3OrganizationTransformer.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerTransformer.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleTransformer.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/LocationSamples.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/Stu3LocationTransformerTest.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/OrganizationSamples.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/organization/Stu3OrganizationTransformerTest.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerSamples.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerTransformerTest.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/PractitionerRoleSamples.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/Stu3PractitionerRoleTransformerTest.java
Avoid nulls for STU3 Practitioner Identifier and PractitionerRole Specialty.
A change to the practitioner name used in SystemDefinitions triggered a failure in STU3 PractitionerIT, as it caused the search to return more items. Some of these resources in the bundled were not in compliance with STU3 spec, causing the IT failures.
This PR addresses the STU3 spec issues.
Merge FHIR Resources PR first: https://github.com/department-of-veterans-affairs/health-apis-fhir-resources/pull/133
=> API-7988: STU3 Practitioner identifier and specialty fix

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerController.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerControllerTest.java
Add support to DSTU2 practitioner to migrate IDs without the `:S` suffix
See https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/752
To minimize conflicts when https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/751 re-merges, `Dstu2PractitionerControllerTest.java` includes all of the refactoring from that PR
=> API-7971 dstu2 practitioner read migration support

data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PractitionerIT.java
All Practitioner ITs have been re-enabled, but `Practitioner?identifier=http://hl7.org/fhir/sid/us-npi|` does not finish and must stay disabled.
Follow-up to investigate: https://vajira.max.gov/browse/API-8040
=> API-8037 disable practitioner system-only IT

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/LocationEntity.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerEntity.java
Confirmed with @nmoisan that references in the `Practitioner` and `Location` datamart resources are now fully populated
=> API-8016 remove practitioner and location datamart reference defaulting

data-query-tests/pom.xml, data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PractitionerIT.java, data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PractitionerRoleIT.java, data-query/pom.xml, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleController.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleControllerTest.java
Adds support to `R4PractitionerRoleController` for the search parameters:
- `practitioner.identifier` - allows for NPI or cdw id
- `practitioner.name`
=> API-3701: practitioner role search by practitioner identifer and name

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerController.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformer.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/PractitionerRoleRepository.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerControllerTest.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformerTest.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitioner/PractitionerSamples.java
Update `Dstu2PractitionerController` and `Dstu2PractitionerTransformer` to use `DatamartPractitionerRole` and stop using the embedded `DatamartPractitioner.PractitionerRole` class
=> API-7562 use PractitionerRoleEntity for DSTU2 Practitioner

data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/Dstu2PatientTransformer.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/GenderMapping.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/Dstu2PatientTransformerTest.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/GenderMappingTest.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformerTest.java
Refactored some switch statements for less lines of code.
Note: I had to `@SuppressWarnings(UnneccessaryParenthesis)` for the new switches, error prone is being dumb.
Added more relaxed gender mappings for both dstu2 and r4 patient, and supporting unit tests.
Mappings : https://vajira.max.gov/browse/API-8340?workflowName=Lighthouse+Default+Workflow&stepId=8
=> relaxed gender mappings

data-query-tests/src/main/java/gov/va/api/health/dataquery/tests/SystemDefinitions.java, data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PractitionerRoleIT.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/PractitionerRoleRepository.java, data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleController.java, data-query/src/test/java/gov/va/api/health/dataquery/service/controller/practitionerrole/R4PractitionerRoleControllerTest.java
Adds `specialty` search param to R4 PractitionerRole
Examples:
```
/r4/PractitionerRole?specialty=207Q00000X
/r4/PractitionerRole?specialty=http://nucc.org/provider-taxonomy|207Q00000X
```
=> API-8343 practitioner role search by specialty
